### ISSUE TITLE
Use BioImage.IO RDF spec

### ISSUE THREAD

**Issue by oeway** [HenriquesLab/DL4MicEverywhere#20]
Not sure exactly, but won't it be great if you can adopt our RDF spec: https://github.com/bioimage-io/spec-bioimage-io/blob/gh-pages/rdf_spec_latest.md for the notebook yaml file? The only required fields are `type`, `format_version`, `name` and `description`, for example, this notebook rdf file will be like this:
```yaml
source: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/Colab_notebooks/Cellpose_2D_ZeroCostDL4Mic.ipynb # <-------------change to source
requirements_url: https://raw.githubusercontent.com/HenriquesLab/ZeroCostDL4Mic/master/requirements_files/Cellpose_2D_requirements_simple.txt
cuda_version: 11.8.0
ubuntu_version: 22.04
python_version: 3.10
sections_to_remove: 1.1. 1.2. 2. 6.3. 
version: 0.1.0
description: "Cellpose_2D_DL4Mic is the conversion of the CellPose 2D notebook from ZeroCostDL4Mic."
name: "Cellpose 2D DL4Mic" # <------------added name
format_version: "0.2.3" # <-------------added format version
type: "application"  # <-------------added type
tags: ["notebook", "ZeroCostDL4Mic"]  # <-------------added tags with notebook
```

Like this we will be able to list it in the model zoo, if that's useful at all.
